### ISSUE TITLE
How to use unit test in blog?

### ISSUE THREAD

**Issue by sam80719** [Clement-Jean/grpc-go-course#1]
Hi Clement-Jean:

I finished gRPC-GO from the udemy course, but I noticed that you have written tests, will you add the same course?
Or README.md can be updated
I also noticed that some French and French courses are different

like  this struct
`
type server struct { // The original course is to write service
	pb.BlogServiceServer
}
`

**Comment by Clement-Jean** [comment]
Hey, I'm not sure what is the question here. Do you mean you want to run the tests in blog or something ?

**Comment by sam80719** [comment]
Sorry I didn't make it clear.
I would like to use the test in the folder blog, so I use some cmd in the blog folder.
` go test -v -cover=true service_test.go
`
then error like this
`
# command-line-arguments [command-line-arguments.test]
./service_test.go:19:35: undefined: Service
FAIL    command-line-arguments [build failed]
FAIL
`

**Comment by Clement-Jean** [comment]
Normally, you would run something like: `go test ./blog/server` at the root level. This will run all the tests in the blog directory. If you want to run a specific test, you will have to include the file called server.go. Like so: `go test ./blog/server/server_test.go ./blog/server/server.go`. Let me know if it helps.

**Comment by sam80719** [comment]
It's work!!!

Thank you so much it is a great honor to be your student in udemy.
